### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by fredster33**

### CODE REVIEW

**Comment by pbatard** [comment]
Thanks for the Pull Request. Unfortunately this requires a bit more involvement than simply fixing the English page, as all the translations also need to be updated, and a small alteration like this usually results in GetText failing to match the English version of the text with its translation... Basically every single `github` that's used in any translation (including `.po` and `.mo` files) needs to be replaced with `GitHub`. But one also needs to make sure that links to GitHub (`https://(.*)github.com(.*)`) are **not** altered.

This is going to require quite a bit of work, so I'm probably going to delay this low priority request for some time...

**Comment by fredster33** [comment]
Oop. I'll create a little regex and clone locally. It'll probably take roughly 2 hours for me to get back to a computer and commit, and I'll be done.

**Comment by pbatard** [comment]
You'll need to regenerate the `.mo`... which aren't text files.

For the record [here](https://github.com/pbatard/rufus-web/commit/bb76ea1f3c4e329f35eaf9bab74d6e9fd7ad3358) is what an update like yours should look like (where we switched our CD/DVD burning applications recommendations). So that's more than 150 files that need to get updated...

I used [this python script](https://github.com/pbatard/rufus-web/blob/bb76ea1f3c4e329f35eaf9bab74d6e9fd7ad3358/locale/update.py) to go through the `.po`/`.mo` update, and I'm planning to reuse something similar to go through yours, so you don't have to bother.

It's just going to take me a while to do so, even with a script, because it's low priority.

And yeah, I'd like to move away from this madness of having to internally use gettext on a local server to ultimately generate static pages that can be served by GitHub, [but GitHub are not at all sympathetic to adding proper localization support to GitHub pages](https://github.com/github/pages-gem/issues/401#issuecomment-847001971).

**Comment by fredster33** [comment]
Ah, got it. Yeah, the Jekyll localization support is really bad. Well, thanks, I'll wait for you to use the script. This is definitely low priority :)

**Comment by fredster33** [comment]
Going to close this PR for now, assuming that you'll push commits to the main repo

**Comment by pbatard** [comment]
I'd rather keep it open, as it's low priority and, even if I'm not going to apply this PR as is, I need a reminder that I have some work to do here. 😉

Unfortunately, since you deleted your branch, I can't reopen this PR so I created issue #16.

**Pull request closed without merging**
